name: Print Txt file

on: 
  push:
    branches:
      - main
      - tanvir
  pull_request:
    branches:
      - main  


jobs:
   read_the_file: 
      runs-on:  self-hosted
      steps:
        - name: Git Checkout korte hobe
          uses: actions/checkout@v2
        - name: Read the Txt file
          run: | 
            /home/ubuntu/.nvm/versions/node/v25.3.0/bin/pm2 status

           
